### ISSUE TITLE
/denseores_identifyblock reports incorrect modid.

### ISSUE THREAD

**Issue by Thiana** [rwtema/DenseOres#121]
/denseores_identifyblock is reporting the incorrect modids (ie, funores instead of FunOres, resourcefulcrops instead of ResourcefulCrops). JEI is doing the same thing so I'm wondering if forge is lowercasing the modids?

Thanks.

**Comment by WenXin20** [comment]
If you use the WIT Mod (Similar to waila) and sneak when looking at a block will show the modid of the block

**Comment by Thiana** [comment]
You can also see the incorrect casing in WIT  for *items*, as it's also using `GameData.getItemRegistry().getNameForObject()`. For *blocks* though, it uses `net.minecraftforge.fml.common.ModContainer.getModID()` which returns the unaltered modid.
