### ISSUE TITLE
1.10.2?

### ISSUE THREAD

**Issue by MakeLord95** [rwtema/DenseOres#129]
Can we have an update so we can use this on 1.10.2...

**Comment by charlesbevans** [comment]
There's a version that's supposed to work through CompatLayer being discussed in #132. Apparently, there's a bug in it right now though.

**Comment by MakeLord95** [comment]
Yea, I noticed it a few days ago, and tested. Didn't get it to run and decided to wait for a while. I ran into the same problem mentioned in #132
