### ISSUE TITLE
[1.7.10] Probability config does literally nothing

### ISSUE THREAD

**Issue by KryptonCaptain** [rwtema/DenseOres#131]
I've been trying to get dense ores and [strata](https://minecraft.curseforge.com/projects/strata) (though I've been using a custom fork on my git which fixes the texture gen issue) to play nicely together for the last couple of days, but with little success
In trying to get dense strata ores to both register and generate, I seem to have found an issue that also extends to things such as the railcraft abyssal/dark ores. The blocks are registered, and have the correct textures - but don't actually seem to generate in the world.

Using my RC block configs as an example:

```
block_18 {
        S:baseBlock=Railcraft:ore
        I:baseBlockMeta=2
        S:baseBlockTexture=railcraft:ore.dark.diamond
        D:denseOreProbability=100
        I:renderType=0
        I:retroGenID=1
        I:retroGenId=0
        S:underlyingBlock=railcraft:cube.stone.abyssal
    }

    block_19 {
        S:baseBlock=Railcraft:ore
        I:baseBlockMeta=3
        S:baseBlockTexture=railcraft:ore.dark.emerald
        D:denseOreProbability=100
        I:renderType=0
        I:retroGenID=1
        I:retroGenId=0
        S:underlyingBlock=railcraft:cube.stone.abyssal
    }

    block_20 {
        S:baseBlock=Railcraft:ore
        I:baseBlockMeta=4
        S:baseBlockTexture=railcraft:ore.dark.lapis
        D:denseOreProbability=100
        I:renderType=0
        I:retroGenID=1
        I:retroGenId=0
        S:underlyingBlock=railcraft:cube.stone.abyssal
    }
```
Strata test config
```
    block_48 {
        S:baseBlock=strata:block.minecraft.redstone_ore.0
        I:baseBlockMeta=1
        S:baseBlockTexture=strata:minecraft/redstone_ore.1.minecraft.stone
        D:denseOreProbability=100
        I:renderType=0
        I:retroGenID=0
        I:retroGenId=0
        S:underlyingBlock=strata:minecraft/stone.1
    }
```

Now, assuming I've config'd it all correctly, the dark/strata ores should generate as dense 100% of the time. Except that they don't generate at all, and only the normal blocks do.

Any help? Finding a solution to this might also find a solution to getting dense strata ores - though that could also have something to do with whether it or this is running its chunk gen first. I've also tried changing the load order on strata, to have it register after dense ores, and then stratify the dense ores, but that didn't seem to work either, possibly for the aforementioned reason

**Comment by KryptonCaptain** [comment]
Closed because I fixed it myself

**Comment by Breadabix** [comment]
Can I ask how you got this working?

**Comment by KryptonCaptain** [comment]
A really inefficient hack that replaces how dense ore already generates.
https://github.com/KryptonCaptain/DenseOres/blob/7ce98b640f934a8f27f0df6247e51c3b1d534f2f/src/main/java/com/rwtema/denseores/WorldGenOres.java#L34
Wouldn't really recommend using it, as it'll probably slow world gen a bit - but it technically does work.
