### ISSUE TITLE
Texture PermaCache

### ISSUE THREAD

**Issue by BrainInBlack** [rwtema/DenseOres#79]
I was wondering if there is a way to perma-cache the generated textures, to speed up client load time after the first start, or even right away if a pack creator generates the textures in advance?

**Comment by Entoarox** [comment]
Please see https://github.com/rwtema/DenseOres/blob/master/src/main/resources/assets/denseores/textures/blocks/customTextures.txt for an answer to both of your questions.

**Comment by BrainInBlack** [comment]
Ah good to know, thank you.
