### ISSUE TITLE
Startup Crash, blocks generating beyond the id limits

### ISSUE THREAD

**Issue by AegisLesha** [rwtema/DenseOres#86]
Crashlog: http://pastebin.com/pn6yehaV
Seems to also happen with AOBD, Storage Drawers Addons and Woodstuff ( @ganymedes01 , @jaquadro )

**Comment by ganymedes01** [comment]
If you went over the ID limit your only option is to remove some mods...

**Comment by AegisLesha** [comment]
Changing Java's allocated memory or PermGen could also solve the issue, right?

**Comment by ganymedes01** [comment]
No, the block ID limit has nothing to do with the amount of memory you have.
It will be 8714 even if you give it 1 terabyte of RAM.

**Comment by AegisLesha** [comment]
I guess I can close the issue then...

**Comment by AegisLesha** [comment]
Interestingly enough, it doesn't happen when AgriCraft is not present @InfinityRider

**Comment by ganymedes01** [comment]
Whatever mod that you remove that releases enough IDs will allow you to load your game back :P

**Comment by AegisLesha** [comment]
Oracle, fix your Java D:

**Comment by Adaptivity** [comment]
https://github.com/fewizz/NotEnoughIDs/releases say goodbye to id range exceeded. But this incompatible with old worlds.

**Comment by AegisLesha** [comment]
I don't mind deleting worlds, I'm testing mods at the moment

'Incompatible with Fastcraft' is quite sad, though :-(

**Comment by Adaptivity** [comment]
Yeah, I know.
